### ISSUE TITLE
Inquiry on Replicating ImageNet w4a8 Results

### ISSUE THREAD

**Issue by mason5957** [BienLuky/EDA-DM#2]
Thank you very much for sharing your code.

I am currently attempting to replicate the ImageNet w4a8 results presented in your paper. Following the instructions you provided, the outcomes I've achieved thus differ from the results reported in your paper, with an FID of only 13.7. 

Could you please advise if there are any specific aspects that I should pay attention to or adjust, such as the number of iterations or other parameters?

**Comment by BienLuky** [comment]
Thank you for your attention. Under the premise of guaranteeing that the generated image is 50000, λ and γ can be adjusted appropriately, e.g., by turning up λ. The number of iteration steps of the experiment does not need to be adjusted.

**Comment by BienLuky** [comment]
I can provide the quantized model cheakpoint for you if you need them.

**Comment by mason5957** [comment]
Thank you very much for your willingness to provide the quantized model checkpoint. If it's convenient for you, could you please share the checkpoints for LSUN Bedroom, LSUN Church, and ImageNet? If possible, it would be greatly appreciated if you could also include the code for loading the checkpoints.

Additionally, the number of generated images is 50,000. The only modification I made was setting "--n_batch 25" due to the limitations of the VRAM size on my 3090.

`python ./scripts/sample_diffusion_ldm_imagenet.py --cond --ptq --no_grad_ckpt \
--split --ddim_steps 20 --ddim_eta 0.0 --ckpt models/ldm/cin256-v2/model.ckpt \
--config configs/latent-diffusion/cin256-v2.yaml --logdir result/imagenet \
--device cuda:0 --skip_grid --n_samples 50000 --n_batch 25 --weight_bit 4 \
--quant_act --act_bit 8 --sm_abit 8 --calib_t_mode normal --calib_num_samples 1024 \
--batch_samples 64 --calib_im_mode greedy --lamda 0.5 --recon --lr_w 5e-1 --lr_a 1e-4 --add_loss 1.3 \`

Thank you once again for your assistance!

**Comment by mason5957** [comment]
Should you require my Gmail address, it is masonlin369.ee11@nycu.edu.tw.

**Comment by mason5957** [comment]
@BienLuky 
It seems like the checkpoints provided in the README require authentication for download. 
Could you please make them accessible without requiring authentication? 

Additionally, could you kindly provide the checkpoints for LSUN Bedroom and LSUN Church? 
Thank you very much.

 ![螢幕擷取畫面 2024-04-05 222940](https://github.com/BienLuky/EDA-DM/assets/76578150/506b7d72-05ba-4504-ab69-00d51f98d600)

**Comment by BienLuky** [comment]
Thanks for the heads up. You can download it now. Other cheakpoints will be opened later.

**Comment by mason5957** [comment]
@BienLuky 
I encountered an issue of missing keys while trying to load the checkpoint you provided. 
Could you please also share the code you used to save and load the model whenever it's convenient for you? 

Thank you very much!

`RuntimeError: Error(s) in loading state_dict for QuantModel:
        Missing key(s) in state_dict: "model.time_embed.0.weight", "model.time_embed.0.bias", "model.time_embed.0.weight_quantizer.alpha", "model.ti
me_embed.0.weight_quantizer.zero_point", "model.time_embed.0.weight_quantizer.delta", "model.time_embed.0.act_quantizer.delta", "model.time_embed.2.
weight", "model.time_embed.2.bias", "model.time_embed.2.weight_quantizer.alpha", "model.time_embed.2.weight_quantizer.zero_point", "model.time_embed
.2.weight_quantizer.delta", "model.time_embed.2.act_quantizer.delta", "model.input_blocks.0.0.weight", "model.input_blocks.0.0.bias", "model.input_b
locks.0.0.weight_quantizer.alpha", ...`

**Comment by BienLuky** [comment]
ok！torch.save(sampler.model.model.state_dict(), os.path.join('…', "Imagenet_W4A8_ckpt.pth"))

**Comment by mason5957** [comment]
Thank you for providing the information. I have resolved the issue.
